services:
  - type: web
    name: convertidor-joel
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y libreoffice
    startCommand: gunicorn wsgi:app
